/**
 * Cookie 格式化基础模块
 * 提供将Cookie数据转换为不同输出格式的功能
 * 
 * 该模块包含以下主要功能:
 * 1. 将Cookie数据格式化为多种输出格式 (JSON, CSV, XML, Netscape)
 */

import { Utils } from '../../utils/utils.js';

/**
 * 格式化 Cookies 数据为指定格式
 * 根据传入的格式参数，将Cookie数据转换为相应的格式
 * 
 * @param {Array|Object} cookies - Cookies 数据，可以是数组或按域名分组的对象
 * @param {string} format - 目标格式 (json, csv, xml, netscape)
 * @param {boolean} isGrouped - 是否已按域名分组，影响格式化方式
 * @returns {Object} 格式化后的数据对象，包含对应格式的属性
 */
function formatCookiesData(cookies, format, isGrouped) {
  switch (format) {
    case 'csv':
      return { csv: cookiesToCsv(cookies, isGrouped) };
    case 'xml':
      return { xml: cookiesToXml(cookies, isGrouped) };
    case 'netscape':
      return { netscape: cookiesToNetscape(cookies, isGrouped) };
    default: // json
      // 如果是分组的cookies，需要先展开
      if (isGrouped && typeof cookies === 'object' && cookies !== null) {
        // 将分组的cookies展开为数组
        return Object.values(cookies).flat();
      }
      // 直接返回cookies数组
      return cookies;
  }
}

/**
 * 将 Cookies 转换为 CSV 格式
 * CSV格式遵循Netscape Cookie文件格式标准，包含7个字段:
 * domain, flag, path, secure, expiration, name, value
 * 
 * @param {Array|Object} cookies - Cookies 数据
 * @param {boolean} isGrouped - 是否已按域名分组
 * @returns {string} CSV 格式的字符串，包含头部和数据行
 */
function cookiesToCsv(cookies, isGrouped) {
  // 定义CSV头部字段
  const headers = ['domain', 'flag', 'path', 'secure', 'expiration', 'name', 'value'];
  // 添加头部行
  let csvContent = headers.join(',') + '\n';
  
  /**
   * 将单个Cookie对象格式化为CSV行
   * @param {Object} cookie - Cookie对象
   * @returns {string} CSV格式的行数据
   */
  function formatCookieAsCsv(cookie) {
    const fields = [
      `"${cookie.domain || ''}"`,           // 域名，用引号包围
      cookie.httpOnly ? 'TRUE' : 'FALSE',   // HttpOnly标志
      `"${cookie.path || '/'}"`,            // 路径，用引号包围
      cookie.secure ? 'TRUE' : 'FALSE',     // 安全标志
      cookie.expirationDate ? Math.floor(Number(cookie.expirationDate)) : 0, // 过期时间戳
      `"${cookie.name || ''}"`,             // Cookie名称，用引号包围
      `"${cookie.value || ''}"`             // Cookie值，用引号包围
    ];
    return fields.join(',');
  }
  
  // 根据数据是否分组采用不同的处理方式
  if (isGrouped) {
    // 处理分组的 cookies (按域名分组的对象)
    Object.values(cookies).forEach(group => {
      group.forEach(cookie => {
        csvContent += formatCookieAsCsv(cookie) + '\n';
      });
    });
  } else {
    // 处理未分组的 cookies (Cookie对象数组)
    if (Array.isArray(cookies)) {
      cookies.forEach(cookie => {
        csvContent += formatCookieAsCsv(cookie) + '\n';
      });
    }
  }
  
  return csvContent;
}

/**
 * 将 Cookies 转换为 XML 格式
 * XML格式具有良好的结构化特性，便于程序解析和人类阅读
 * 
 * @param {Array|Object} cookies - Cookies 数据
 * @param {boolean} isGrouped - 是否已按域名分组
 * @returns {string} XML 格式的字符串
 */
function cookiesToXml(cookies, isGrouped) {
  // 添加XML声明和根元素
  let xmlContent = '<?xml version="1.0" encoding="UTF-8"?>\n<cookies>\n';
  
  /**
   * 将单个Cookie对象格式化为XML节点
   * @param {Object} cookie - Cookie对象
   * @param {string} indent - 缩进字符串，用于格式化输出
   * @returns {string} XML格式的节点字符串
   */
  function formatCookieAsXml(cookie, indent = '  ') {
    return `${indent}<cookie>\n` +
      `${indent}  <domain>${Utils.escapeXml(cookie.domain || '')}</domain>\n` +
      `${indent}  <flag>${cookie.httpOnly ? 'TRUE' : 'FALSE'}</flag>\n` +
      `${indent}  <path>${Utils.escapeXml(cookie.path || '/')}</path>\n` +
      `${indent}  <secure>${cookie.secure ? 'TRUE' : 'FALSE'}</secure>\n` +
      `${indent}  <expiration>${cookie.expirationDate ? Math.floor(Number(cookie.expirationDate)) : 0}</expiration>\n` +
      `${indent}  <name>${Utils.escapeXml(cookie.name || '')}</name>\n` +
      `${indent}  <value>${Utils.escapeXml(cookie.value || '')}</value>\n` +
      `${indent}</cookie>\n`;
  }
  
  // 根据数据是否分组采用不同的处理方式
  if (isGrouped) {
    // 处理分组的 cookies
    Object.entries(cookies).forEach(([domain, group]) => {
      // 为每个域名添加包装元素
      xmlContent += `  <domain name="${Utils.escapeXml(domain)}">\n`;
      group.forEach(cookie => {
        xmlContent += formatCookieAsXml(cookie, '    ');
      });
      xmlContent += `  </domain>\n`;
    });
  } else {
    // 处理未分组的 cookies
    if (Array.isArray(cookies)) {
      cookies.forEach(cookie => {
        xmlContent += formatCookieAsXml(cookie);
      });
    }
  }
  
  xmlContent += '</cookies>';
  return xmlContent;
}

/**
 * 将 Cookies 转换为 Netscape Cookie 格式
 * Netscape格式是广泛支持的标准Cookie文件格式，兼容curl等工具
 * 
 * @param {Array|Object} cookies - Cookies 数据
 * @param {boolean} isGrouped - 是否已按域名分组
 * @returns {string} Netscape Cookie 格式的字符串
 */
function cookiesToNetscape(cookies, isGrouped) {
  // 添加文件头注释
  let netscapeContent = '# Netscape HTTP Cookie File\n' +
    '# http://curl.haxx.se/rfc/cookie_spec.html\n' +
    '# This file was generated by Cookie Export Tool\n\n';
  
  /**
   * 将单个Cookie对象格式化为Netscape格式行
   * Netscape格式: domain flag path secure expiration name value (7个字段，用制表符分隔)
   * @param {Object} cookie - Cookie对象
   * @returns {string} Netscape格式的行数据
   */
  function formatCookieAsNetscape(cookie) {
    // Netscape 格式: domain flag path secure expiration name value
    const domain = cookie.domain || '';                     // 域名
    const flag = cookie.httpOnly ? 'TRUE' : 'FALSE';        // HttpOnly标志 (TRUE/FALSE)
    const path = cookie.path || '/';                        // 路径
    const secure = cookie.secure ? 'TRUE' : 'FALSE';        // 安全标志 (TRUE/FALSE)
    const expiration = cookie.expirationDate ? Math.floor(Number(cookie.expirationDate)) : 0; // 过期时间戳
    const name = cookie.name || '';                         // Cookie名称
    const value = cookie.value || '';                       // Cookie值
    
    // 用制表符连接各字段
    return `${domain}\t${flag}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`;
  }
  
  // 根据数据是否分组采用不同的处理方式
  if (isGrouped) {
    // 处理分组的 cookies
    Object.values(cookies).forEach(group => {
      group.forEach(cookie => {
        netscapeContent += formatCookieAsNetscape(cookie) + '\n';
      });
    });
  } else {
    // 处理未分组的 cookies
    if (Array.isArray(cookies)) {
      cookies.forEach(cookie => {
        netscapeContent += formatCookieAsNetscape(cookie) + '\n';
      });
    }
  }
  
  return netscapeContent;
}

// 导出所有函数，使其可以在其他模块中使用
export const CookieFormatterBase = {
  formatCookiesData,
  cookiesToCsv,
  cookiesToXml,
  cookiesToNetscape
};